# Generated by Django 4.2.6 on 2023-12-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('my_files', models.FileField(upload_to='MyNotes')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='signupmaster',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
