# Generated by Django 4.2.6 on 2023-12-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='msg',
            field=models.TextField(),
        ),
    ]
